### ISSUE TITLE
Metadata Component

### ISSUE THREAD

**Issue by arcticicestudio** [nordtheme/web#101]
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/50351078-59da4280-0541-11e9-97ec-b983c43bbedc.png" width="20%" /> <img src="https://user-images.githubusercontent.com/7836623/50351088-6199e700-0541-11e9-831d-0b9200abfbe9.png" width="20%" /></p>

> Associated epic: #100

This issue documents the implementation of the core atom `SiteMetadata` that injects global metadata like documented in the [“SEO & Social Media Representation” design concept][gh-100]. Next to general data like the page title and canonical URL it will include data for the [Open Graph Protocol][og] and [Twitter Cards][tw-docs-cards].
The component won't render any UI, but injects the elements into the `<head>` using [React Helmet][gh-rh].

For more details read the great documentation about [SEO with Gatsby][gb-docs-seo].

## Tasks

- [x] Implement the represented data as project-wide entity.
- [x] Implement the `SiteMetadata` component.
- [x] Add the `SiteMetadata` component to existing pages.

[gb-docs-seo]: https://www.gatsbyjs.org/docs/seo
[gh-100]: https://github.com/arcticicestudio/nord-docs/issues/100
[gh-rh]: https://github.com/nfl/react-helmet
[og]: http://ogp.me
[tw-docs-cards]: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html
